In [1]:
from src.configs.paths import PROCESSED_DATA_DIR
from src.io.io_utils import load_parquet
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)

In [12]:
path_dataset = PROCESSED_DATA_DIR / "cicids2017/friday.parquet"
df = load_parquet(path_dataset)

In [3]:
display(df.shape)
df.info(verbose=True)# false para visão mais enxuta

(549856, 79)

<class 'pandas.DataFrame'>
Index: 549856 entries, 42 to 767048
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            549856 non-null  int64
 1   expiration_id                 549856 non-null  int64
 2   src_ip                        549856 non-null  str
 3   src_mac                       549856 non-null  str
 4   src_oui                       549856 non-null  str
 5   src_port                      549856 non-null  int64
 6   dst_ip                        549856 non-null  str
 7   dst_mac                       549856 non-null  str
 8   dst_oui                       549856 non-null  str
 9   dst_port                      549856 non-null  int64
 10  protocol                      549856 non-null  int64
 11  ip_version                    549856 non-null  int64
 12  vlan_id                       549856 non-null  int64
 13  bidirectional_first_seen_ms   549856 non-null  int64
 14  bidirectional_last_seen_ms    549856 non-null  int64
 15  bidirectional_duration_ms     549856 non-null  int64
 16  bidirectional_packets         549856 non-null  int64
 17  bidirectional_bytes           549856 non-null  int64
 18  src2dst_first_seen_ms         549856 non-null  int64
 19  src2dst_last_seen_ms          549856 non-null  int64
 20  src2dst_duration_ms           549856 non-null  int64
 21  src2dst_packets               549856 non-null  int64
 22  src2dst_bytes                 549856 non-null  int64
 23  dst2src_first_seen_ms         549856 non-null  int64
 24  dst2src_last_seen_ms          549856 non-null  int64
 25  dst2src_duration_ms           549856 non-null  int64
 26  dst2src_packets               549856 non-null  int64
 27  dst2src_bytes                 549856 non-null  int64
 28  bidirectional_min_ps          549856 non-null  int64
 29  bidirectional_mean_ps         549856 non-null  float64
 30  bidirectional_stddev_ps       549856 non-null  float64
 31  bidirectional_max_ps          549856 non-null  int64
 32  src2dst_min_ps                549856 non-null  int64
 33  src2dst_mean_ps               549856 non-null  float64
 34  src2dst_stddev_ps             549856 non-null  float64
 35  src2dst_max_ps                549856 non-null  int64
 36  dst2src_min_ps                549856 non-null  int64
 37  dst2src_mean_ps               549856 non-null  float64
 38  dst2src_stddev_ps             549856 non-null  float64
 39  dst2src_max_ps                549856 non-null  int64
 40  bidirectional_min_piat_ms     549856 non-null  int64
 41  bidirectional_mean_piat_ms    549856 non-null  float64
 42  bidirectional_stddev_piat_ms  549856 non-null  float64
 43  bidirectional_max_piat_ms     549856 non-null  int64
 44  src2dst_min_piat_ms           549856 non-null  int64
 45  src2dst_mean_piat_ms          549856 non-null  float64
 46  src2dst_stddev_piat_ms        549856 non-null  float64
 47  src2dst_max_piat_ms           549856 non-null  int64
 48  dst2src_min_piat_ms           549856 non-null  int64
 49  dst2src_mean_piat_ms          549856 non-null  float64
 50  dst2src_stddev_piat_ms        549856 non-null  float64
 51  dst2src_max_piat_ms           549856 non-null  int64
 52  bidirectional_syn_packets     549856 non-null  int64
 53  bidirectional_cwr_packets     549856 non-null  int64
 54  bidirectional_ece_packets     549856 non-null  int64
 55  bidirectional_urg_packets     549856 non-null  int64
 56  bidirectional_ack_packets     549856 non-null  int64
 57  bidirectional_psh_packets     549856 non-null  int64
 58  bidirectional_rst_packets     549856 non-null  int64
 59  bidirectional_fin_packets     549856 non-null  int64
 60  src2dst_syn_packets           549856 non-null  int64
 61  src2dst_cwr_packets           549856 non-null  int64
 62  src2dst_ece_packets           549856 non-null  int64
 63  src2dst_urg_packets           549856 non-null  int64
 64  src2dst_ack_packets           549856 non-null  int64
 65  src2dst_psh_packets           549856 non-null  int64
 66  src2dst_rst_packets           549856 non-null  int64
 67  src2dst_fin_packets           549856 non-null  int64
 68  dst2src_syn_packets           549856 non-null  int64
 69  dst2src_cwr_packets           549856 non-null  int64
 70  dst2src_ece_packets           549856 non-null  int64
 71  dst2src_urg_packets           549856 non-null  int64
 72  dst2src_ack_packets           549856 non-null  int64
 73  dst2src_psh_packets           549856 non-null  int64
 74  dst2src_rst_packets           549856 non-null  int64
 75  dst2src_fin_packets           549856 non-null  int64
 76  flow_key                      549856 non-null  str
 77  flow_key_rev                  549856 non-null  str
 78  label                         549856 non-null  str
dtypes: float64(12), int64(58), str(9)
memory usage: 417.0 MB

In [4]:
display(df.head())

      id  expiration_id         src_ip            src_mac   src_oui  src_port          dst_ip            dst_mac   dst_oui  dst_port  protocol  ip_version  vlan_id  bidirectional_first_seen_ms  bidirectional_last_seen_ms  bidirectional_duration_ms  bidirectional_packets  bidirectional_bytes  src2dst_first_seen_ms  src2dst_last_seen_ms  src2dst_duration_ms  src2dst_packets  src2dst_bytes  dst2src_first_seen_ms  dst2src_last_seen_ms  dst2src_duration_ms  dst2src_packets  dst2src_bytes  bidirectional_min_ps  bidirectional_mean_ps  bidirectional_stddev_ps  bidirectional_max_ps  src2dst_min_ps  src2dst_mean_ps  src2dst_stddev_ps  src2dst_max_ps  dst2src_min_ps  dst2src_mean_ps  dst2src_stddev_ps  dst2src_max_ps  bidirectional_min_piat_ms  bidirectional_mean_piat_ms  bidirectional_stddev_piat_ms  bidirectional_max_piat_ms  src2dst_min_piat_ms  src2dst_mean_piat_ms  src2dst_stddev_piat_ms  src2dst_max_piat_ms  dst2src_min_piat_ms  dst2src_mean_piat_ms  dst2src_stddev_piat_ms  dst2src_max_piat_ms  bidirectional_syn_packets  bidirectional_cwr_packets  bidirectional_ece_packets  bidirectional_urg_packets  bidirectional_ack_packets  bidirectional_psh_packets  bidirectional_rst_packets  bidirectional_fin_packets  src2dst_syn_packets  src2dst_cwr_packets  src2dst_ece_packets  src2dst_urg_packets  src2dst_ack_packets  src2dst_psh_packets  src2dst_rst_packets  src2dst_fin_packets  dst2src_syn_packets  dst2src_cwr_packets  dst2src_ece_packets  dst2src_urg_packets  dst2src_ack_packets  dst2src_psh_packets  dst2src_rst_packets  dst2src_fin_packets                                  flow_key                              flow_key_rev   label
42    42              0  192.168.10.14  b8:ac:6f:36:07:ee  b8:ac:6f     49415    192.168.10.3  18:66:da:9b:e3:7d  18:66:da        88         6           4        0                1499428848902               1499428848903                          1                     16                 1568          1499428848902         1499428848903                    1                8            810          1499428848902         1499428848903                    1                8            758                    40              98.000000                96.963223                   273              40       101.250000         106.135695             273              40        94.750000          94.116569             247                          0                    0.066667                      0.258199                          1                    0              0.142857                0.377964                    1                    0              0.142857                0.377964                    1                          4                          0                          0                          0                         14                          4                          2                          2                    2                    0                    0                    0                    6                    2                    0                    2                    2                    0                    0                    0                    8                    2                    2                    0     192.168.10.14|192.168.10.3|49415|88|6     192.168.10.3|192.168.10.14|88|49415|6  BENIGN
49    49              0  192.168.10.14  b8:ac:6f:36:07:ee  b8:ac:6f     49422    192.168.10.3  18:66:da:9b:e3:7d  18:66:da     49671         6           4        0                1499428849012               1499428849332                        320                     34                 6502          1499428849012         1499428849332                  320               20           3838          1499428849012         1499428849280                  268               14           2664                    40             191.235294               220.268027                   800              40       191.900000         221.390082             800              52       190.285714         226.989471             720                          0                    9.696970                     38.512567                        212                    0             16.842105               50.155606                  212                    0             20.615385               74.029880                  267                          4                          0                          0                          0                         32                         24                          0                          0                    2                    0                    0                    0                   18                   12                    0                    0                    2                    0                    0                    0                   14                   12                    0                    0  192.168.10.14|192.168.10.3|49422|49671|6  192.168.10.3|192.168.10.14|49671|49422|6  BENIGN
50    50              0  192.168.10.25  00:25:00:a8:c4:60  00:25:00       138  192.168.10.255  ff:ff:ff:ff:ff:ff  ff:ff:ff       138        17           4        0                1499428841949               1499428841950                          1                     12                 2928          1499428841949         1499428841950                    1               12           2928                      0                     0                    0                0              0                   244             244.000000                 0.000000                   244             244       244.000000           0.000000             244               0         0.000000           0.000000               0                          0                    0.090909                      0.301511                          1                    0              0.090909                0.301511                    1                    0              0.000000                0.000000                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0   192.168.10.25|192.168.10.255|138|138|17   192.168.10.255|192.168.10.25|138|138|17  BENIGN
107  107              0  192.168.10.14  b8:ac:6f:36:07:ee  b8:ac:6f     49413    192.168.10.3  18:66:da:9b:e3:7d  18:66:da     49666         6           4        0                1499428848898               1499428861520                      12622                     94                27924          1499428848898         1499428861520                12622               48          18694          1499428848898         1499428861458                12560               46           9230                    40             297.063830               394.863657                  1789              40       389.458333         530.585624            1789              40       200.652174          97.919971             340                          0                  135.720430                    894.993883                       6310                    0            268.553191             1251.231373                 6310                    0            279.111111             1291.333282                 6373                          4                          0                          0                          0                         92                         76                          0                          0                    2                    0                    0                    0                   46                   38                    0                    0                    2                    0                    0                    0                   46                   38                    0                    0  192.168.10.14|192.168.10.3|49413|49666|6  192.168.10.3|192.168.10.14|49666|49413|6  BENIGN
109  109              0  192.168.10.14  b8:ac:6f:36:07:ee  b8:ac:6f     54608    192.168.10.3  18:66:da:9b:e3:7d  18:66:da        53        17           4        0                1499428850100               1499428850124                         24                      4                  280          1499428850100         1499428850100                    0                2            124          1499428850124         1499428850124                    0                2            156                    62              70.000000                 9.237604                    78              62        62.000000           0.000000              62              78        78.000000           0.000000              78                          0                    8.000000                     13.856406                         24                    0              0.000000                0.000000                    0                    0              0.000000                0.000000                    0                          0                          0                          0                          0                          0                          0                          0                          0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0                    0    192.168.10.14|192.168.10.3|54608|53|17    192.168.10.3|192.168.10.14|53|54608|17  BENIGN

In [5]:
df["label"].value_counts()

label
BENIGN      314722
PortScan    158616
DDoS         75318
Bot           1200
Name: count, dtype: int64

In [13]:
(df.isnull().sum() / len(df)) * 100
#ajustar quantidade de linhas por exibição pd.set_alguma_coisa...

id                              0.0
expiration_id                   0.0
src_ip                          0.0
src_mac                         0.0
src_oui                         0.0
src_port                        0.0
dst_ip                          0.0
dst_mac                         0.0
dst_oui                         0.0
dst_port                        0.0
protocol                        0.0
ip_version                      0.0
vlan_id                         0.0
bidirectional_first_seen_ms     0.0
bidirectional_last_seen_ms      0.0
bidirectional_duration_ms       0.0
bidirectional_packets           0.0
bidirectional_bytes             0.0
src2dst_first_seen_ms           0.0
src2dst_last_seen_ms            0.0
src2dst_duration_ms             0.0
src2dst_packets                 0.0
src2dst_bytes                   0.0
dst2src_first_seen_ms           0.0
dst2src_last_seen_ms            0.0
dst2src_duration_ms             0.0
dst2src_packets                 0.0
dst2src_bytes                   0.0
bidirectional_min_ps            0.0
bidirectional_mean_ps           0.0
bidirectional_stddev_ps         0.0
bidirectional_max_ps            0.0
src2dst_min_ps                  0.0
src2dst_mean_ps                 0.0
src2dst_stddev_ps               0.0
src2dst_max_ps                  0.0
dst2src_min_ps                  0.0
dst2src_mean_ps                 0.0
dst2src_stddev_ps               0.0
dst2src_max_ps                  0.0
bidirectional_min_piat_ms       0.0
bidirectional_mean_piat_ms      0.0
bidirectional_stddev_piat_ms    0.0
bidirectional_max_piat_ms       0.0
src2dst_min_piat_ms             0.0
src2dst_mean_piat_ms            0.0
src2dst_stddev_piat_ms          0.0
src2dst_max_piat_ms             0.0
dst2src_min_piat_ms             0.0
dst2src_mean_piat_ms            0.0
dst2src_stddev_piat_ms          0.0
dst2src_max_piat_ms             0.0
bidirectional_syn_packets       0.0
bidirectional_cwr_packets       0.0
bidirectional_ece_packets       0.0
bidirectional_urg_packets       0.0
bidirectional_ack_packets       0.0
bidirectional_psh_packets       0.0
bidirectional_rst_packets       0.0
bidirectional_fin_packets       0.0
src2dst_syn_packets             0.0
src2dst_cwr_packets             0.0
src2dst_ece_packets             0.0
src2dst_urg_packets             0.0
src2dst_ack_packets             0.0
src2dst_psh_packets             0.0
src2dst_rst_packets             0.0
src2dst_fin_packets             0.0
dst2src_syn_packets             0.0
dst2src_cwr_packets             0.0
dst2src_ece_packets             0.0
dst2src_urg_packets             0.0
dst2src_ack_packets             0.0
dst2src_psh_packets             0.0
dst2src_rst_packets             0.0
dst2src_fin_packets             0.0
flow_key                        0.0
flow_key_rev                    0.0
label                           0.0
dataset_name                    0.0
dtype: float64

In [7]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe().T

                                 count          mean           std           min           25%           50%           75%           max
id                            549856.0  3.718562e+05  2.222831e+05  4.200000e+01  1.715505e+05  3.528955e+05  5.747248e+05  7.670480e+05
expiration_id                 549856.0  5.856079e-04  2.419227e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00
src_port                      549856.0  4.655050e+04  1.624065e+04  0.000000e+00  3.971400e+04  5.193600e+04  5.794200e+04  6.553500e+04
dst_port                      549856.0  2.053028e+03  7.573679e+03  0.000000e+00  5.300000e+01  8.000000e+01  4.430000e+02  6.552500e+04
protocol                      549856.0  8.900132e+00  4.856969e+00  1.000000e+00  6.000000e+00  6.000000e+00  1.700000e+01  1.320000e+02
ip_version                    549856.0  4.002430e+00  6.966749e-02  4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00  6.000000e+00
vlan_id                       549856.0  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
bidirectional_first_seen_ms   549856.0  1.499445e+12  8.400501e+06  1.499429e+12  1.499437e+12  1.499450e+12  1.499452e+12  1.499458e+12
bidirectional_last_seen_ms    549856.0  1.499445e+12  8.400728e+06  1.499429e+12  1.499437e+12  1.499450e+12  1.499452e+12  1.499458e+12
bidirectional_duration_ms     549856.0  2.113002e+03  6.912013e+03  0.000000e+00  0.000000e+00  3.700000e+01  8.400000e+02  1.199990e+05
bidirectional_packets         549856.0  1.127231e+01  8.821821e+02  1.000000e+00  2.000000e+00  4.000000e+00  9.000000e+00  4.630880e+05
bidirectional_bytes           549856.0  8.740381e+03  1.243079e+06  2.800000e+01  1.000000e+02  2.530000e+02  9.760000e+02  6.436159e+08
src2dst_first_seen_ms         549856.0  1.499445e+12  8.400501e+06  1.499429e+12  1.499437e+12  1.499450e+12  1.499452e+12  1.499458e+12
src2dst_last_seen_ms          549856.0  1.499445e+12  8.400735e+06  1.499429e+12  1.499437e+12  1.499450e+12  1.499452e+12  1.499458e+12
src2dst_duration_ms           549856.0  2.069993e+03  6.898352e+03  0.000000e+00  0.000000e+00  0.000000e+00  7.330000e+02  1.199990e+05
src2dst_packets               549856.0  5.715020e+00  4.595017e+02  1.000000e+00  1.000000e+00  2.000000e+00  5.000000e+00  2.656160e+05
src2dst_bytes                 549856.0  2.215597e+03  8.618758e+05  2.800000e+01  5.200000e+01  1.120000e+02  3.120000e+02  5.889380e+08
dst2src_first_seen_ms         549856.0  1.457073e+12  2.484732e+11  0.000000e+00  1.499436e+12  1.499449e+12  1.499452e+12  1.499458e+12
dst2src_last_seen_ms          549856.0  1.457073e+12  2.484732e+11  0.000000e+00  1.499436e+12  1.499449e+12  1.499452e+12  1.499458e+12
dst2src_duration_ms           549856.0  1.509709e+03  6.686903e+03  0.000000e+00  0.000000e+00  0.000000e+00  1.800000e+02  1.199980e+05
dst2src_packets               549856.0  5.557288e+00  4.307937e+02  0.000000e+00  1.000000e+00  1.000000e+00  4.000000e+00  2.330860e+05
dst2src_bytes                 549856.0  6.524785e+03  8.742128e+05  0.000000e+00  5.200000e+01  1.370000e+02  4.940000e+02  6.363629e+08
bidirectional_min_ps          549856.0  5.072232e+01  1.685430e+01  2.800000e+01  4.000000e+01  4.100000e+01  5.800000e+01  1.387000e+03
bidirectional_mean_ps         549856.0  2.182463e+02  3.101957e+02  2.800000e+01  5.000000e+01  7.100000e+01  1.585000e+02  2.142796e+03
bidirectional_stddev_ps       549856.0  3.625598e+02  7.641977e+02  0.000000e+00  2.828427e+00  1.414214e+01  1.339453e+02  4.693083e+03
bidirectional_max_ps          549856.0  1.218573e+03  2.590991e+03  2.800000e+01  5.200000e+01  8.600000e+01  3.080000e+02  2.486000e+04
src2dst_min_ps                549856.0  5.311831e+01  2.257392e+01  2.800000e+01  4.000000e+01  5.200000e+01  6.000000e+01  1.500000e+03
src2dst_mean_ps               549856.0  7.421753e+01  1.208085e+02  2.800000e+01  4.400000e+01  5.466667e+01  7.000000e+01  5.815833e+03
src2dst_stddev_ps             549856.0  3.644177e+01  1.885666e+02  0.000000e+00  0.000000e+00  0.000000e+00  7.708993e+00  7.018229e+03
src2dst_max_ps                549856.0  1.502296e+02  4.914145e+02  2.800000e+01  5.200000e+01  6.000000e+01  7.300000e+01  2.486000e+04
dst2src_min_ps                549856.0  7.029649e+01  5.984655e+01  0.000000e+00  4.000000e+01  5.200000e+01  8.000000e+01  1.500000e+03
dst2src_mean_ps               549856.0  4.171997e+02  7.571883e+02  0.000000e+00  4.600000e+01  7.600000e+01  2.078393e+02  3.909000e+03
dst2src_stddev_ps             549856.0  4.773397e+02  1.144387e+03  0.000000e+00  0.000000e+00  0.000000e+00  2.655811e+01  6.690915e+03
dst2src_max_ps                549856.0  1.181078e+03  2.568717e+03  0.000000e+00  5.200000e+01  8.300000e+01  2.460000e+02  1.308400e+04
bidirectional_min_piat_ms     549856.0  1.760995e+01  1.018990e+02  0.000000e+00  0.000000e+00  0.000000e+00  2.300000e+01  8.990000e+03
bidirectional_mean_piat_ms    549856.0  2.187942e+02  5.578346e+02  0.000000e+00  0.000000e+00  2.400000e+01  1.140000e+02  8.990000e+03
bidirectional_stddev_piat_ms  549856.0  4.771657e+02  1.053790e+03  0.000000e+00  0.000000e+00  0.000000e+00  1.358546e+02  7.054097e+03
bidirectional_max_piat_ms     549856.0  1.443241e+03  2.881376e+03  0.000000e+00  0.000000e+00  3.600000e+01  5.070000e+02  9.999000e+03
src2dst_min_piat_ms           549856.0  1.513889e+02  1.156545e+03  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.038700e+04
src2dst_mean_piat_ms          549856.0  4.301173e+02  1.353240e+03  0.000000e+00  0.000000e+00  0.000000e+00  1.080000e+02  1.038700e+04
src2dst_stddev_piat_ms        549856.0  5.213622e+02  1.155229e+03  0.000000e+00  0.000000e+00  0.000000e+00  5.827828e+01  7.149557e+03
src2dst_max_piat_ms           549856.0  1.415289e+03  2.883008e+03  0.000000e+00  0.000000e+00  0.000000e+00  4.590000e+02  1.040600e+04
dst2src_min_piat_ms           549856.0  2.300288e+02  1.311181e+03  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.331200e+04
dst2src_mean_piat_ms          549856.0  4.278194e+02  1.479590e+03  0.000000e+00  0.000000e+00  0.000000e+00  2.900556e+01  1.331200e+04
dst2src_stddev_piat_ms        549856.0  3.272904e+02  9.987767e+02  0.000000e+00  0.000000e+00  0.000000e+00  1.760173e+01  8.570687e+03
dst2src_max_piat_ms           549856.0  9.558211e+02  2.459235e+03  0.000000e+00  0.000000e+00  0.000000e+00  1.100000e+02  1.806600e+04
bidirectional_syn_packets     549856.0  7.026567e-01  9.026503e-01  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  1.200000e+01
bidirectional_cwr_packets     549856.0  2.691614e-04  3.828536e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  2.300000e+01
bidirectional_ece_packets     549856.0  2.273322e-04  2.102101e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  2.000000e+00
bidirectional_urg_packets     549856.0  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
bidirectional_ack_packets     549856.0  9.795046e+00  8.821836e+02  0.000000e+00  0.000000e+00  2.000000e+00  8.000000e+00  4.630880e+05
bidirectional_psh_packets     549856.0  1.590578e+00  1.079560e+01  0.000000e+00  0.000000e+00  0.000000e+00  2.000000e+00  4.619000e+03
bidirectional_rst_packets     549856.0  3.797958e-01  8.035452e-01  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  1.010000e+02
bidirectional_fin_packets     549856.0  3.977841e-01  7.684585e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+01
src2dst_syn_packets           549856.0  4.439617e-01  5.295864e-01  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  9.000000e+00
src2dst_cwr_packets           549856.0  2.655241e-04  3.823785e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  2.300000e+01
src2dst_ece_packets           549856.0  1.200314e-04  1.095524e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00
src2dst_urg_packets           549856.0  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
src2dst_ack_packets           549856.0  4.690395e+00  4.594979e+02  0.000000e+00  0.000000e+00  1.000000e+00  4.000000e+00  2.656160e+05
src2dst_psh_packets           549856.0  7.310423e-01  7.657906e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  4.504000e+03
src2dst_rst_packets           549856.0  1.799035e-01  7.255858e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.010000e+02
src2dst_fin_packets           549856.0  1.196022e-01  3.503408e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  8.000000e+00
dst2src_syn_packets           549856.0  2.586950e-01  4.650206e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  8.000000e+00
dst2src_cwr_packets           549856.0  3.637316e-06  1.907173e-03  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00
dst2src_ece_packets           549856.0  1.073008e-04  1.035806e-02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00
dst2src_urg_packets           549856.0  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
dst2src_ack_packets           549856.0  5.104651e+00  4.307981e+02  0.000000e+00  0.000000e+00  1.000000e+00  4.000000e+00  2.330860e+05
dst2src_psh_packets           549856.0  8.595360e-01  5.244837e+00  0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  1.137000e+03
dst2src_rst_packets           549856.0  1.998923e-01  4.205042e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  5.000000e+00
dst2src_fin_packets           549856.0  2.781819e-01  5.444735e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  8.000000e+00

In [9]:
num_cols = df.select_dtypes(include="number").columns
cat_cols = df.select_dtypes(include=["object", "string"]).columns
id_cols = ["flow_key", "flow_key_rev"]
aux_cols = ["ts_ms"]

len(num_cols), len(cat_cols)

(70, 9)

In [10]:
df["bidirectional_duration_ms"].min(), df["bidirectional_duration_ms"].max()
#aparentemente essa coluna foi dropada em algum momento. melhor usar o tempo do nfstream

(np.int64(0), np.int64(119999))