In [17]:

import src.utils.notebook_ploting as nb_plot
import src.utils.features as features
from src.utils.notebook_setup import *

from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import LabelEncoder

setup_pandas()

In [18]:
df = load_dataset()
df = df.sample(100000, random_state=1)
# essa amostra leva em torno de 25 s

In [19]:
numerical_features, categorical_features = features.split_features(df)

In [20]:
# separar features de label. Verificar o que fazer com as categóricas
    # transformar categóricas em flags binárias (provavelmente vai aumentar bastante o número de colunas)
features_df = df[numerical_features].copy()
target = df["label"]

In [21]:
features_df

         bidirectional_duration_ms  bidirectional_packets  bidirectional_bytes  bidirectional_mean_ps  bidirectional_stddev_ps  bidirectional_max_ps  bidirectional_mean_piat_ms  bidirectional_stddev_piat_ms  bidirectional_max_piat_ms  bidirectional_syn_packets  bidirectional_psh_packets  bidirectional_rst_packets  bidirectional_fin_packets
354732                           0                      2                  100                  50.00                    14.14                    60                        0.00                          0.00                          0                          1                          0                          1                          0
1015152                         35                     29                21722                 749.03                  1043.43                  2960                        1.25                          5.18                         27                          4                          4                          0                          4
1970024                        402                     16                13033                 814.56                  1818.29                  7292                       26.80                         59.76                        201                          2                          3                          2                          2
841409                       10812                    424               456254                1076.07                   780.40                  2888                       25.56                        486.27                       9997                          2                         18                          0                          0
124498                         972                     26                14872                 572.00                   660.22                  1755                       38.88                         73.85                        328                          2                          7                          0                          2
...                            ...                    ...                  ...                    ...                      ...                   ...                         ...                           ...                        ...                        ...                        ...                        ...                        ...
1187221                        157                      8                 1506                 188.25                   212.47                   664                       22.43                         27.98                         53                          0                          5                          0                          0
1513747                         15                      2                   80                  40.00                     0.00                    40                       15.00                          0.00                         15                          0                          0                          0                          0
1530280                         51                      2                   93                  46.50                     7.78                    52                       51.00                          0.00                         51                          0                          0                          0                          0
626507                         350                     13                 4654                 358.00                   653.28                  2082                       29.17                         41.81                         87                          2                          4                          0                          2
324678                           0                      2                  100                  50.00                    14.14                    60                        0.00                          0.00                          0                          1                          0                          1                          0

[100000 rows x 13 columns]

In [22]:
# encoding do target (categorias → números)
# label_encoder possui o mapeamento e pode ser reutilizado
label_encoder = LabelEncoder()
target_encoded = label_encoder.fit_transform(target)

In [23]:
# tratamento de valores inválidos (provavelmente será necessário se houver algum tratamento de dado que gere um inf ou nan)
#features_df.isna().any().any()
#np.isinf(features_df).any().any()
#features_df = features_df.replace([np.inf, -np.inf], np.nan)
#features_df = features_df.fillna(features_df.median())

In [24]:
# cálculo da mutual information
    # mede o quão uma feature ajuda a prever o label
    # a partir de qual valor descartar essas features? (aparentemente apenas treinando um modelo para saber)
        # lembrete: treinar modelo com as melhores features top 10, 15, 20 ... verificar métrica (verificar com michael)
# random state funciona como seed para garantir reprodutibilidade do experimento
#
#array com scores
mi_scores = mutual_info_classif(features_df, target_encoded, random_state=1)
# mapeamento das features com mi_score
mi_scores_by_feature = pd.Series(mi_scores, index=features_df.columns).sort_values(ascending=False)

In [25]:
mi_scores_by_feature

bidirectional_bytes            0.10
bidirectional_mean_ps          0.10
bidirectional_max_ps           0.09
bidirectional_stddev_ps        0.09
bidirectional_stddev_piat_ms   0.05
bidirectional_mean_piat_ms     0.05
bidirectional_max_piat_ms      0.05
bidirectional_packets          0.04
bidirectional_duration_ms      0.04
bidirectional_rst_packets      0.03
bidirectional_fin_packets      0.03
bidirectional_psh_packets      0.03
bidirectional_syn_packets      0.03
dtype: float64

In [26]:
# dataframe final
# transforma o mapeamento em  tabela
mi_dataframe = mi_scores_by_feature.reset_index()
#display(mi_dataframe)
mi_dataframe.columns = ["feature", "mutual_information"]

In [27]:

# filtro por mi
#mi_dataframe = mi_dataframe[mi_dataframe["mutual_information"] > 0.02]
# filtro por top features
#mi_dataframe = mi_dataframe.head(15)

nb_plot.mi_bar_plot(mi_dataframe)

In [28]:
mi_dataframe

                         feature  mutual_information
0            bidirectional_bytes                0.10
1          bidirectional_mean_ps                0.10
2           bidirectional_max_ps                0.09
3        bidirectional_stddev_ps                0.09
4   bidirectional_stddev_piat_ms                0.05
5     bidirectional_mean_piat_ms                0.05
6      bidirectional_max_piat_ms                0.05
7          bidirectional_packets                0.04
8      bidirectional_duration_ms                0.04
9      bidirectional_rst_packets                0.03
10     bidirectional_fin_packets                0.03
11     bidirectional_psh_packets                0.03
12     bidirectional_syn_packets                0.03

In [29]:
top_features = mi_dataframe["feature"].tolist()[:20]
#mi_dataframe[:10]

In [30]:
top_features

['bidirectional_bytes',
 'bidirectional_mean_ps',
 'bidirectional_max_ps',
 'bidirectional_stddev_ps',
 'bidirectional_stddev_piat_ms',
 'bidirectional_mean_piat_ms',
 'bidirectional_max_piat_ms',
 'bidirectional_packets',
 'bidirectional_duration_ms',
 'bidirectional_rst_packets',
 'bidirectional_fin_packets',
 'bidirectional_psh_packets',
 'bidirectional_syn_packets']

In [31]:
top_features_df = features_df[top_features]
corr_matrix = top_features_df.corr(method="pearson")
nb_plot.correlation_heatmap(corr_matrix, is_abs = True)
#display(corre_matrix)