In [2]:
from src.utils.notebook_setup import *
setup_pandas()
import pandas as pd

In [2]:
df = load_dataset()

In [3]:
df['content_type'].sample(10)

374590     NaN
2161428    NaN
964088     NaN
1686320    NaN
375390     NaN
1479431    NaN
146801     NaN
1050037    NaN
1091202    NaN
1185344    NaN
Name: content_type, dtype: str

In [4]:
df['user_agent'].sample(10)

149436     NaN
1229508    NaN
824701     NaN
1798668    NaN
490673     NaN
22811      NaN
1257545    NaN
470654     NaN
1087006    NaN
614562     NaN
Name: user_agent, dtype: str

In [5]:
df['server_fingerprint'].sample(10)

408495                                  NaN
2157934                                 NaN
967494                                  NaN
1140537    860fcf58fd757e26aa8911e5eaff6b53
526051                                  NaN
59635      6f0a5b0a36320bdd6b88ed3e0b6c4152
1656210                                 NaN
1001065    ab41313cfec25328b20865eb1388e0a2
1822763                                 NaN
386989                                  NaN
Name: server_fingerprint, dtype: str

In [6]:
df['client_fingerprint'].sample(10)

1728372                                     NaN
748831                                      NaN
107649     t12d1509h2_073e58a039a6_e70312a1ce2c
41440                                       NaN
833741                                      NaN
796004                                      NaN
923883                                      NaN
1649937                                     NaN
899861                                      NaN
307594                                      NaN
Name: client_fingerprint, dtype: str

In [7]:
df['requested_server_name'].sample(10)

518953                                        NaN
1369820                138.36.192.54.in-addr.arpa
233459     member-hsbc-group.webtrends.akadns.net
881883                             px.owneriq.net
966739                           idsync.rlcdn.com
970530                                        NaN
828889                                        NaN
793652                 vars.hotjar.netdna-cdn.com
1595470                            dc.testbed1.ca
1846188                            205.174.165.68
Name: requested_server_name, dtype: str

In [8]:
df["application_name"].sample(10)

2146797                   DNS
1315173                   TLS
407052                Unknown
777836                    TLS
1492997                   TLS
817634                   HTTP
1048282                   DNS
980023     DNS.AWS_Cloudfront
655206                    DNS
2019103                   TLS
Name: application_name, dtype: str

In [9]:
df["application_category_name"].sample(10)

1608881        Web
214185     Network
521823         Web
1656769        Web
1733508        Web
945081         Web
1504725        Web
719755         Web
968150     Network
466709         Web
Name: application_category_name, dtype: str

In [5]:
df = pd.DataFrame(
    [
        [1.0, 0.8, 0.3, 0.1],
        [0.8, 1.0, 0.5, 0.2],
        [0.3, 0.5, 1.0, 0.9],
        [0.1, 0.2, 0.9, 1.0],
    ],
    columns=["col_A", "col_B", "col_C", "col_D"],
    index=["row_A", "row_B", "row_C", "row_D"]
)

import numpy as np
from IPython.display import display

mask = np.triu(np.ones(df.shape), k=1).astype(bool)
upper = df.where(mask)

display(df)
display(upper)
display(upper.stack())
display(upper.stack().reset_index())

       col_A  col_B  col_C  col_D
row_A   1.00   0.80   0.30   0.10
row_B   0.80   1.00   0.50   0.20
row_C   0.30   0.50   1.00   0.90
row_D   0.10   0.20   0.90   1.00

       col_A  col_B  col_C  col_D
row_A    NaN   0.80   0.30   0.10
row_B    NaN    NaN   0.50   0.20
row_C    NaN    NaN    NaN   0.90
row_D    NaN    NaN    NaN    NaN

row_A  col_A    NaN
       col_B   0.80
       col_C   0.30
       col_D   0.10
row_B  col_A    NaN
       col_B    NaN
       col_C   0.50
       col_D   0.20
row_C  col_A    NaN
       col_B    NaN
       col_C    NaN
       col_D   0.90
row_D  col_A    NaN
       col_B    NaN
       col_C    NaN
       col_D    NaN
dtype: float64

   level_0 level_1    0
0    row_A   col_A  NaN
1    row_A   col_B 0.80
2    row_A   col_C 0.30
3    row_A   col_D 0.10
4    row_B   col_A  NaN
5    row_B   col_B  NaN
6    row_B   col_C 0.50
7    row_B   col_D 0.20
8    row_C   col_A  NaN
9    row_C   col_B  NaN
10   row_C   col_C  NaN
11   row_C   col_D 0.90
12   row_D   col_A  NaN
13   row_D   col_B  NaN
14   row_D   col_C  NaN
15   row_D   col_D  NaN